/**
 * 物品：法宝 / 丹药 / 灵物 / 功法
 * 稀有度 1 凡品 / 2 灵品 / 3 仙品 / 4 神品
 * I001~I005 为既有引用条目，保留原名与效果
 */
export const ITEMS = [
  /* ---- 既有引用条目（勿改） ---- */
  { id: 'I001', name: '青锋剑', kind: '法宝', rarity: 2, desc: '吹毛断发，剑身泛着幽蓝', eff: { hp: 1, breakthrough: 0.03 } },
  { id: 'I002', name: '聚气丹', kind: '丹药', rarity: 1, desc: '入门丹药，服下可增十年苦修', eff: { progress: 20 } },
  { id: 'I003', name: '万年灵参', kind: '灵物', rarity: 3, desc: '参须已成玉色，闻之精神一振', eff: { lifespan: 60, hp: 2 } },
  { id: 'I004', name: '太虚剑诀', kind: '功法', rarity: 4, desc: '残缺的上古剑经，字字如剑', eff: { progressRate: 0.8, iq: 2 } },
  { id: 'I005', name: '护心镜', kind: '法宝', rarity: 2, desc: '挡住过一次致命一击的旧物', eff: { hp: 2 } },

  /* ---- 凡品 34 件 ---- */
  { id: 'I006', name: '生锈铁剑', kind: '法宝', rarity: 1, desc: '剑身锈迹斑斑，砍柴倒还趁手', eff: { hp: 1 } },
  { id: 'I007', name: '桃木剑', kind: '法宝', rarity: 1, desc: '道观门口买的，据说能辟邪', eff: { hp: 1 } },
  { id: 'I008', name: '粗布护腕', kind: '法宝', rarity: 1, desc: '缝了三层粗布，挡挡拳脚', eff: { hp: 1 } },
  { id: 'I009', name: '柴刀', kind: '法宝', rarity: 1, desc: '砍了十年柴，刃口卷了又卷', eff: { hp: 1 } },
  { id: 'I010', name: '竹节灵笛', kind: '法宝', rarity: 1, desc: '吹起来跑调，倒也能静心', eff: { progress: 10 } },
  { id: 'I011', name: '铜铃', kind: '法宝', rarity: 1, desc: '摇一摇，山里的野兽就退了', eff: { hp: 1 } },
  { id: 'I012', name: '旧罗盘', kind: '法宝', rarity: 1, desc: '指针总是乱转，风水先生也摇头', eff: { progress: 10 } },
  { id: 'I013', name: '麻绳符', kind: '法宝', rarity: 1, desc: '绳子系着一道朱砂符，聊胜于无', eff: { hp: 1 } },
  { id: 'I014', name: '缺口铁盾', kind: '法宝', rarity: 1, desc: '盾面一个豁口，是替人挡的', eff: { hp: 1 } },
  { id: 'I015', name: '草编护身符', kind: '法宝', rarity: 1, desc: '奶奶编的，说能保平安', eff: { hp: 1 } },
  { id: 'I016', name: '回气散', kind: '丹药', rarity: 1, desc: '药铺一包三文，气短时抿一口', eff: { progress: 18 } },
  { id: 'I017', name: '补血丹', kind: '丹药', rarity: 1, desc: '黑乎乎一颗，专治跌打损伤', eff: { hp: 1 } },
  { id: 'I018', name: '醒神散', kind: '丹药', rarity: 1, desc: '闻一下，瞌睡虫全跑光了', eff: { progress: 12 } },
  { id: 'I019', name: '驱寒汤', kind: '丹药', rarity: 1, desc: '一碗下肚，寒气从脚底散了', eff: { hp: 1 } },
  { id: 'I020', name: '壮骨丸', kind: '丹药', rarity: 1, desc: '骨头缝里都透着股结实劲', eff: { hp: 1 } },
  { id: 'I021', name: '苦修丹', kind: '丹药', rarity: 1, desc: '苦得皱眉，修行却不敢停', eff: { progress: 15 } },
  { id: 'I022', name: '清热丸', kind: '丹药', rarity: 1, desc: '上火时含一颗，心里就静了', eff: { progress: 10 } },
  { id: 'I023', name: '安神香', kind: '丹药', rarity: 1, desc: '睡前点一炷，一夜无梦', eff: { progress: 12 } },
  { id: 'I024', name: '糙米灵米', kind: '灵物', rarity: 1, desc: '带壳的灵米，熬粥顶饱', eff: { hp: 1 } },
  { id: 'I025', name: '十年药草', kind: '灵物', rarity: 1, desc: '药农采的，晒干还带着土气', eff: { progress: 15 } },
  { id: 'I026', name: '露水灵石', kind: '灵物', rarity: 1, desc: '指甲盖大，握久了有点温', eff: { progress: 20 } },
  { id: 'I027', name: '山泉葫芦', kind: '灵物', rarity: 1, desc: '装的是山泉，喝一口透心凉', eff: { hp: 1 } },
  { id: 'I028', name: '暖玉', kind: '灵物', rarity: 1, desc: '巴掌大的暖玉，冬天捂手正好', eff: { hp: 1 } },
  { id: 'I029', name: '风干兽肉', kind: '灵物', rarity: 1, desc: '硬得硌牙，嚼着却有力量', eff: { hp: 1 } },
  { id: 'I030', name: '灵植种子', kind: '灵物', rarity: 1, desc: '不知会长出什么，先种下', eff: { progress: 12 } },
  { id: 'I031', name: '陈年灵酒', kind: '灵物', rarity: 1, desc: '埋了十年的酒，入口一线火', eff: { progress: 15 } },
  { id: 'I032', name: '吐纳诀', kind: '功法', rarity: 1, desc: '睡前练两遍，一夜无梦', eff: { progress: 15 } },
  { id: 'I033', name: '五禽戏图', kind: '功法', rarity: 1, desc: '照着画练，筋骨一天天开了', eff: { progress: 10 } },
  { id: 'I034', name: '清心咒', kind: '功法', rarity: 1, desc: '心里烦时念三遍，人就静了', eff: { progress: 14 } },
  { id: 'I035', name: '铁布衫残页', kind: '功法', rarity: 1, desc: '只练到胸口，刀砍留道白印', eff: { hp: 1 } },
  { id: 'I036', name: '强身拳谱', kind: '功法', rarity: 1, desc: '抄来的拳法，强身健体罢了', eff: { hp: 1 } },
  { id: 'I037', name: '打坐要诀', kind: '功法', rarity: 1, desc: '怎么坐都不对，倒也能入定', eff: { progress: 12 } },
  { id: 'I038', name: '呼吸法门', kind: '功法', rarity: 1, desc: '一吸一呼，把日子过慢了', eff: { progress: 10 } },
  { id: 'I039', name: '晨练剑谱', kind: '功法', rarity: 1, desc: '天不亮就挥剑，挥了十年', eff: { progress: 14 } },

  /* ---- 灵品 33 件 ---- */
  { id: 'I040', name: '青钢剑', kind: '法宝', rarity: 2, desc: '剑身泛着幽蓝，出鞘有一线寒芒', eff: { hp: 1, breakthrough: 0.03 } },
  { id: 'I041', name: '流云靴', kind: '法宝', rarity: 2, desc: '踏上去如踩流云，赶路不觉累', eff: { hp: 1, luck: 1 } },
  { id: 'I042', name: '玄铁护腕', kind: '法宝', rarity: 2, desc: '沉甸甸的，挡过一刀未断', eff: { hp: 2 } },
  { id: 'I043', name: '缚妖索', kind: '法宝', rarity: 2, desc: '浸过黑狗血，勒得住小妖', eff: { hp: 1, breakthrough: 0.03 } },
  { id: 'I044', name: '招魂幡', kind: '法宝', rarity: 2, desc: '风一吹就响，夜里不敢多看', eff: { hp: 1, breakthrough: 0.03 } },
  { id: 'I045', name: '灵光镜', kind: '法宝', rarity: 2, desc: '照见灵气流转，也照见人心', eff: { iq: 1, luck: 1 } },
  { id: 'I046', name: '寒铁短匕', kind: '法宝', rarity: 2, desc: '贴身藏着，刀刃从不沾光', eff: { hp: 1, breakthrough: 0.03 } },
  { id: 'I047', name: '飞针', kind: '法宝', rarity: 2, desc: '十二根柳叶针，出手无声', eff: { hp: 1, breakthrough: 0.04 } },
  { id: 'I048', name: '灵蛇鞭', kind: '法宝', rarity: 2, desc: '鞭身如活蛇，缠上便不松', eff: { hp: 2 } },
  { id: 'I049', name: '定风珠', kind: '法宝', rarity: 2, desc: '含在口中，狂风也近不了身', eff: { hp: 1, luck: 1 } },
  { id: 'I050', name: '阴阳双剑', kind: '法宝', rarity: 2, desc: '一黑一白，合璧时嗡嗡作响', eff: { hp: 1, breakthrough: 0.05 } },
  { id: 'I051', name: '青玉葫芦', kind: '法宝', rarity: 2, desc: '装丹药不潮，装灵液不腐', eff: { progress: 30 } },
  { id: 'I052', name: '聚灵丹', kind: '丹药', rarity: 2, desc: '服下如吞一团暖气，经脉舒张', eff: { progress: 40 } },
  { id: 'I053', name: '洗髓丹', kind: '丹药', rarity: 2, desc: '洗去一身浊气，脱胎换骨', eff: { hp: 1, iq: 1 } },
  { id: 'I054', name: '固元丹', kind: '丹药', rarity: 2, desc: '把根基压得死死的，不易走火', eff: { breakthrough: 0.04 } },
  { id: 'I055', name: '九花玉露丸', kind: '丹药', rarity: 2, desc: '九种灵花酿的丸子，入口生香', eff: { hp: 2 } },
  { id: 'I056', name: '养魂丹', kind: '丹药', rarity: 2, desc: '温养神魂，夜里不再噩梦', eff: { iq: 1, hp: 1 } },
  { id: 'I057', name: '破障丹', kind: '丹药', rarity: 2, desc: '卡关时含一颗，眼前豁然开朗', eff: { breakthrough: 0.06 } },
  { id: 'I058', name: '续命丹', kind: '丹药', rarity: 2, desc: '吊着一口气，够你交代后事', eff: { lifespan: 20 } },
  { id: 'I059', name: '百年灵芝', kind: '灵物', rarity: 2, desc: '菌盖如伞，闻一鼻子都补气', eff: { lifespan: 30, hp: 1 } },
  { id: 'I060', name: '火纹晶', kind: '灵物', rarity: 2, desc: '晶里像有火焰在游走', eff: { hp: 1, progress: 40 } },
  { id: 'I061', name: '玄冰髓', kind: '灵物', rarity: 2, desc: '触手生寒，能镇住心火', eff: { hp: 1, iq: 1 } },
  { id: 'I062', name: '引雷石', kind: '灵物', rarity: 2, desc: '握它练功，经脉常被电流过', eff: { breakthrough: 0.05 } },
  { id: 'I063', name: '阴阳玉', kind: '灵物', rarity: 2, desc: '一半暖一半凉，昼夜不停转', eff: { progress: 50 } },
  { id: 'I064', name: '三叶青莲', kind: '灵物', rarity: 2, desc: '三片叶子，一片一甲子修为', eff: { progress: 60 } },
  { id: 'I065', name: '地心乳', kind: '灵物', rarity: 2, desc: '从地底石缝一滴一滴接的', eff: { hp: 2, lifespan: 20 } },
  { id: 'I066', name: '御风诀', kind: '功法', rarity: 2, desc: '脚下生风，翻墙越脊如平地', eff: { hp: 1, breakthrough: 0.03 } },
  { id: 'I067', name: '金钟罩', kind: '功法', rarity: 2, desc: '运起功来，皮肉如罩金钟', eff: { hp: 2 } },
  { id: 'I068', name: '小五行遁术', kind: '功法', rarity: 2, desc: '借五行之物遁走，遇水则隐', eff: { luck: 1, hp: 1 } },
  { id: 'I069', name: '凝气诀', kind: '功法', rarity: 2, desc: '把散乱灵气拧成一股', eff: { progress: 50 } },
  { id: 'I070', name: '落英剑法', kind: '功法', rarity: 2, desc: '剑落如花瓣，好看也能要命', eff: { hp: 1, breakthrough: 0.04 } },
  { id: 'I071', name: '千钧掌', kind: '功法', rarity: 2, desc: '一掌拍下，青石裂成两半', eff: { hp: 2 } },
  { id: 'I072', name: '龟息功', kind: '功法', rarity: 2, desc: '闭息三日，像死了一样', eff: { lifespan: 40 } },

  /* ---- 仙品 21 件 ---- */
  { id: 'I073', name: '紫电剑', kind: '法宝', rarity: 3, desc: '剑鸣如雷，出鞘自带紫电', eff: { hp: 2, breakthrough: 0.06 } },
  { id: 'I074', name: '山河扇', kind: '法宝', rarity: 3, desc: '扇面绘着万里山河，一扇风起', eff: { iq: 2, progressRate: 0.3 } },
  { id: 'I075', name: '八卦镜', kind: '法宝', rarity: 3, desc: '镜分八卦，照妖照鬼照人心', eff: { hp: 2, breakthrough: 0.06 } },
  { id: 'I076', name: '缚仙绳', kind: '法宝', rarity: 3, desc: '连金丹修士也曾被它捆过', eff: { hp: 2, luck: 2 } },
  { id: 'I077', name: '幽月轮', kind: '法宝', rarity: 3, desc: '月轮悬于掌心，冷光四射', eff: { hp: 3 } },
  { id: 'I078', name: '焚天印', kind: '法宝', rarity: 3, desc: '一方古印，落下时空气都焦了', eff: { hp: 2, breakthrough: 0.08 } },
  { id: 'I079', name: '青鸾羽扇', kind: '法宝', rarity: 3, desc: '青鸾尾羽所制，一扇生清风', eff: { iq: 2, luck: 1 } },
  { id: 'I080', name: '太清丹', kind: '丹药', rarity: 3, desc: '太清之气凝的一颗，服下通体轻盈', eff: { lifespan: 80, progressRate: 0.3 } },
  { id: 'I081', name: '九转金丹', kind: '丹药', rarity: 3, desc: '九转九炼，一丹换一境不是传说', eff: { progress: 150, breakthrough: 0.08 } },
  { id: 'I082', name: '洗尘丹', kind: '丹药', rarity: 3, desc: '洗去尘缘杂念，道心更纯', eff: { iq: 2, luck: 2 } },
  { id: 'I083', name: '悟道丹', kind: '丹药', rarity: 3, desc: '服下枯坐三日，醒来境界不同', eff: { progressRate: 0.4 } },
  { id: 'I084', name: '千年雪莲', kind: '灵物', rarity: 3, desc: '开在雪线之上，瓣如凝脂', eff: { lifespan: 100, hp: 2 } },
  { id: 'I085', name: '龙涎香', kind: '灵物', rarity: 3, desc: '一缕青烟升起，百妖退避', eff: { luck: 3 } },
  { id: 'I086', name: '凤凰木心', kind: '灵物', rarity: 3, desc: '烧不尽的一段木心，暖了千年', eff: { hp: 3, lifespan: 60 } },
  { id: 'I087', name: '星辰砂', kind: '灵物', rarity: 3, desc: '一捧星砂，夜里自己会发光', eff: { progress: 120, iq: 2 } },
  { id: 'I088', name: '空冥石', kind: '灵物', rarity: 3, desc: '石中空空如也，能藏一界', eff: { progressRate: 0.5, hp: 2 } },
  { id: 'I089', name: '太上忘情篇', kind: '功法', rarity: 3, desc: '忘情非无情，是大境界', eff: { progressRate: 0.4, eq: 2 } },
  { id: 'I090', name: '大衍剑典', kind: '功法', rarity: 3, desc: '五十弦翻，一剑一衍', eff: { hp: 2, breakthrough: 0.08 } },
  { id: 'I091', name: '玄天心经', kind: '功法', rarity: 3, desc: '玄天之气沉入丹田，昼夜不息', eff: { progressRate: 0.5, iq: 2 } },
  { id: 'I092', name: '焚诀', kind: '功法', rarity: 3, desc: '引火入体，焚尽经脉杂质', eff: { hp: 2, progress: 100 } },
  { id: 'I093', name: '不动明王印', kind: '功法', rarity: 3, desc: '印结如山，万法加身不动摇', eff: { hp: 3, breakthrough: 0.06 } },

  /* ---- 神品 7 件 ---- */
  { id: 'I094', name: '鸿蒙紫气', kind: '灵物', rarity: 4, desc: '一缕开天时残下的气，游走不定', eff: { progressRate: 1.0, lifespan: 300 } },
  { id: 'I095', name: '混沌青莲', kind: '灵物', rarity: 4, desc: '莲开三十六品，照见万古洪荒', eff: { lifespan: 400, hp: 4 } },
  { id: 'I096', name: '诛仙剑', kind: '法宝', rarity: 4, desc: '剑锋所指，仙神也要避其锋', eff: { breakthrough: 0.15, hp: 4 } },
  { id: 'I097', name: '东皇钟', kind: '法宝', rarity: 4, desc: '一钟镇下，万法俱寂，山河无声', eff: { hp: 5, breakthrough: 0.12 } },
  { id: 'I098', name: '造化玉牒', kind: '功法', rarity: 4, desc: '记着天地初开的第一个字', eff: { progressRate: 1.0, iq: 4 } },
  { id: 'I099', name: '九转还魂丹', kind: '丹药', rarity: 4, desc: '一丹一命，阎王见了也绕道', eff: { lifespan: 500, hp: 4 } },
  { id: 'I100', name: '大罗天经', kind: '功法', rarity: 4, desc: '读了它，才知仙字该怎么写', eff: { progressRate: 0.9, luck: 4 } }
]
