/**
 * 天赋词条（内容扩充版）
 * 见 docs/内容规范.md 第 1 节
 *
 * 稀有度：1 凡品 / 2 灵品 / 3 仙品 / 4 神品
 * tag：智慧 / 体质 / 社交 / 幸运 / 修仙 / 诡异
 * id 范围：T001 ~ T199
 */
export const TALENTS = [
  // ---------------- 凡品（1） 58 条 ----------------
  { id: 'T001', name: '早八诅咒', rarity: 1, tag: '体质', desc: '一上早八就灵魂出窍', eff: { hp: -1, iq: -1, lifespan: -5 } },
  { id: 'T002', name: '熬夜冠军', rarity: 1, tag: '体质', desc: '凌晨三点精神，白天像丧尸', eff: { hp: -1, iq: 1 } },
  { id: 'T003', name: '铁胃', rarity: 1, tag: '体质', desc: '什么都能吃，从没拉过肚子', eff: { hp: 2 } },
  { id: 'T004', name: '路痴', rarity: 1, tag: '智慧', desc: '导航都救不了你，随缘到达', eff: { iq: -1, luck: 1 } },
  { id: 'T005', name: '社恐', rarity: 1, tag: '社交', desc: '人多的地方就浑身难受', eff: { eq: -2, iq: 1 } },
  { id: 'T006', name: '话痨', rarity: 1, tag: '社交', desc: '三天不开口就浑身难受', eff: { eq: 2, luck: -1 } },
  { id: 'T007', name: '咸鱼', rarity: 1, tag: '体质', desc: '能躺着绝不坐着', eff: { hp: 1, luck: -1 } },
  { id: 'T008', name: '吃瓜群众', rarity: 1, tag: '社交', desc: '哪有事都有你', eff: { eq: 1, luck: 1 } },
  { id: 'T009', name: '自来熟', rarity: 1, tag: '社交', desc: '见谁都能聊成老朋友', eff: { eq: 2 } },
  { id: 'T010', name: '手残', rarity: 1, tag: '智慧', desc: '打游戏永远第一个送', eff: { iq: -1, luck: 1 } },
  { id: 'T011', name: '声控', rarity: 1, tag: '社交', desc: '声音好听的人说什么都对', eff: { eq: 1 } },
  { id: 'T012', name: '脸盲', rarity: 1, tag: '智慧', desc: '见过八次还是记不住脸', eff: { iq: -1, eq: 1 } },
  { id: 'T013', name: '手机控', rarity: 1, tag: '智慧', desc: '睡前刷到凌晨是常态', eff: { iq: -1, luck: 1 } },
  { id: 'T014', name: '起床气', rarity: 1, tag: '体质', desc: '早上别和我说话', eff: { hp: 1, eq: -1 } },
  { id: 'T015', name: '干饭王', rarity: 1, tag: '体质', desc: '干饭永远第一个到', eff: { hp: 2, eq: -1 } },
  { id: 'T016', name: '夜猫子', rarity: 1, tag: '体质', desc: '越晚脑子越清醒', eff: { hp: -1, iq: 2 } },
  { id: 'T017', name: '拖延症', rarity: 1, tag: '智慧', desc: '明天一定，明天一定', eff: { iq: -1, hp: 1 } },
  { id: 'T018', name: '强迫症', rarity: 1, tag: '智慧', desc: '桌角必须对齐', eff: { iq: 1, eq: -1 } },
  { id: 'T019', name: '天煞孤星', rarity: 1, tag: '诡异', desc: '亲近的人总会出事', eff: { eq: -3, luck: 2, lifespan: -20 } },
  { id: 'T020', name: '选择困难', rarity: 1, tag: '智慧', desc: '一顿饭能选半小时', eff: { iq: -1, luck: 1 } },
  { id: 'T021', name: '铁头功', rarity: 1, tag: '体质', desc: '撞了南墙也不回头', eff: { hp: 2 } },
  { id: 'T022', name: '话少', rarity: 1, tag: '社交', desc: '一天说不了三句话', eff: { eq: -1, iq: 1 } },
  { id: 'T023', name: '爱笑', rarity: 1, tag: '社交', desc: '笑点低到没有朋友能懂', eff: { eq: 2 } },
  { id: 'T024', name: '泪点低', rarity: 1, tag: '社交', desc: '广告都能看哭', eff: { eq: 1, hp: -1 } },
  { id: 'T025', name: '天选打工人', rarity: 1, tag: '体质', desc: '加班总能精准点到你', eff: { hp: 1, luck: -1 } },
  { id: 'T026', name: '收纳狂', rarity: 1, tag: '智慧', desc: '家里整齐得像样板间', eff: { iq: 1 } },
  { id: 'T027', name: '数码废', rarity: 1, tag: '智慧', desc: '遥控器要研究十分钟', eff: { iq: -1 } },
  { id: 'T028', name: '反方向', rarity: 1, tag: '幸运', desc: '直觉总是反的', eff: { luck: -1, iq: 1 } },
  { id: 'T029', name: '口味重', rarity: 1, tag: '体质', desc: '无辣不欢，胃在流泪', eff: { hp: -1, luck: 1 } },
  { id: 'T030', name: '记性好', rarity: 1, tag: '智慧', desc: '别人三年前的话都记得', eff: { iq: 2 } },
  { id: 'T031', name: '耳背', rarity: 1, tag: '智慧', desc: '你说什么，再说一遍', eff: { iq: -1, eq: 1 } },
  { id: 'T032', name: '大嗓门', rarity: 1, tag: '社交', desc: '隔着两条街都能听见', eff: { eq: 2, iq: -1 } },
  { id: 'T033', name: '体弱多病', rarity: 1, tag: '体质', desc: '风一吹就倒下', eff: { hp: -3, lifespan: -40 } },
  { id: 'T034', name: '抗冻', rarity: 1, tag: '体质', desc: '冬天一件单衣走天下', eff: { hp: 2 } },
  { id: 'T035', name: '药罐子', rarity: 1, tag: '体质', desc: '从小喝药比喝水多', eff: { hp: -2, iq: 1, lifespan: -30 } },
  { id: 'T036', name: '招猫体质', rarity: 1, tag: '幸运', desc: '猫见你就翻肚皮', eff: { luck: 2 } },
  { id: 'T037', name: '天生绝脉', rarity: 1, tag: '诡异', desc: '经脉闭塞，此生与仙无缘', eff: { forbidCultivation: true, hp: 2, lifespan: -30 } },
  { id: 'T038', name: '命薄', rarity: 1, tag: '诡异', desc: '体弱多病，大夫直摇头', eff: { dieChance: 0.03, hp: -1, lifespan: -40 } },
  { id: 'T039', name: '手气好', rarity: 1, tag: '幸运', desc: '抽卡永远是欧皇', eff: { luck: 2 } },
  { id: 'T040', name: '方向感强', rarity: 1, tag: '智慧', desc: '走一遍就记住路', eff: { iq: 1, luck: 1 } },
  { id: 'T041', name: '慢性子', rarity: 1, tag: '体质', desc: '你急你的，我不急', eff: { hp: 1, eq: -1 } },
  { id: 'T042', name: '急性子', rarity: 1, tag: '体质', desc: '排队超过三分钟就走', eff: { hp: -1, iq: 1 } },
  { id: 'T043', name: '到点就睡', rarity: 1, tag: '体质', desc: '到点必须睡，雷打不动', eff: { hp: 1 } },
  { id: 'T044', name: '假笑大师', rarity: 1, tag: '社交', desc: '心里骂人，脸上开花', eff: { eq: 2, iq: -1 } },
  { id: 'T045', name: '孤僻', rarity: 1, tag: '社交', desc: '独来独往，人多了就烦', eff: { eq: -3, iq: 2 } },
  { id: 'T046', name: '厚脸皮', rarity: 1, tag: '社交', desc: '被拒绝八次还能再问', eff: { eq: 2, iq: -1 } },
  { id: 'T047', name: '爱睡懒觉', rarity: 1, tag: '体质', desc: '周末能睡到下午', eff: { hp: 2, eq: -1 } },
  { id: 'T048', name: '失眠', rarity: 1, tag: '体质', desc: '躺下就清醒，天亮才困', eff: { hp: -1, iq: 1 } },
  { id: 'T049', name: '诡异缠身', rarity: 1, tag: '诡异', desc: '总觉得有什么跟着你', eff: { forbidCultivation: true, iq: 2, eq: -2, lifespan: -20 } },
  { id: 'T050', name: '胃不好', rarity: 1, tag: '体质', desc: '三餐不规律的下场', eff: { hp: -2, iq: 1 } },
  { id: 'T051', name: '霉运缠身', rarity: 1, tag: '幸运', desc: '喝凉水都塞牙', eff: { luck: -3, hp: -1 } },
  { id: 'T052', name: '近视眼', rarity: 1, tag: '智慧', desc: '摘了眼镜六亲不认', eff: { iq: 1, hp: -1 } },
  { id: 'T053', name: '大长腿', rarity: 1, tag: '体质', desc: '走路带风，天生衣架子', eff: { hp: 2, eq: 1 } },
  { id: 'T054', name: '吃不胖', rarity: 1, tag: '体质', desc: '怎么吃都不长肉', eff: { hp: 1, eq: 1 } },
  { id: 'T055', name: '灵根浅薄', rarity: 1, tag: '修仙', desc: '灵根淡得几乎看不见', eff: { spiritRoot: 'pseudo', iq: -1 } },
  { id: 'T056', name: '打坐习惯', rarity: 1, tag: '修仙', desc: '一坐就是一下午', eff: { progressRate: 0.2, hp: 1 } },
  { id: 'T057', name: '草木亲近', rarity: 1, tag: '修仙', desc: '草木见你都格外精神', eff: { daoHeart: 2, progressRate: 0.2 } },
  { id: 'T058', name: '吐纳有法', rarity: 1, tag: '修仙', desc: '呼吸之间自有章法', eff: { progressRate: 0.25, hp: 1 } },

  // ---------------- 灵品（2） 42 条 ----------------
  { id: 'T059', name: '过目不忘', rarity: 2, tag: '智慧', desc: '看一遍就记住，考试不复习', eff: { iq: 2, luck: 1 } },
  { id: 'T060', name: '铜皮铁骨', rarity: 2, tag: '体质', desc: '皮糙肉厚，很少生病', eff: { hp: 3 } },
  { id: 'T061', name: '逻辑鬼才', rarity: 2, tag: '智慧', desc: '一眼看穿谎言的漏洞', eff: { iq: 3 } },
  { id: 'T062', name: '心算快', rarity: 2, tag: '智慧', desc: '结账前先算出总价', eff: { iq: 2, luck: 1 } },
  { id: 'T063', name: '人脉王', rarity: 2, tag: '社交', desc: '到哪都有认识的人', eff: { eq: 3 } },
  { id: 'T064', name: '谈判专家', rarity: 2, tag: '社交', desc: '买菜都能砍下两块钱', eff: { eq: 2, iq: 1 } },
  { id: 'T065', name: '万人迷', rarity: 2, tag: '社交', desc: '走到哪都有人递水', eff: { eq: 2, luck: 1 } },
  { id: 'T066', name: '乐天派', rarity: 2, tag: '社交', desc: '天塌了先睡一觉', eff: { eq: 2, hp: 1 } },
  { id: 'T067', name: '抗压王', rarity: 2, tag: '体质', desc: '越忙越冷静', eff: { hp: 2, eq: 1 } },
  { id: 'T068', name: '铁人', rarity: 2, tag: '体质', desc: '连轴转三天不喊累', eff: { hp: 3, eq: -1 } },
  { id: 'T069', name: '运动细胞', rarity: 2, tag: '体质', desc: '校运会永远第一名', eff: { hp: 3 } },
  { id: 'T070', name: '手艺人', rarity: 2, tag: '智慧', desc: '什么坏了都能修', eff: { iq: 2, luck: 1 } },
  { id: 'T071', name: '语感好', rarity: 2, tag: '智慧', desc: '外语听两遍就会说', eff: { iq: 2, eq: 1 } },
  { id: 'T072', name: '音乐天才', rarity: 2, tag: '智慧', desc: '听一遍就能扒谱', eff: { iq: 2, eq: 1 } },
  { id: 'T073', name: '绘画天赋', rarity: 2, tag: '智慧', desc: '随手一画就很好看', eff: { iq: 2, luck: 1 } },
  { id: 'T074', name: '第六感', rarity: 2, tag: '幸运', desc: '觉得要出事就真出事', eff: { luck: 2, luckRate: 0.2 } },
  { id: 'T075', name: '欧皇', rarity: 2, tag: '幸运', desc: '抽奖从没空过手', eff: { luck: 3, luckRate: 0.25 } },
  { id: 'T076', name: '逢凶化吉', rarity: 2, tag: '幸运', desc: '总能擦着边躲过灾祸', eff: { luck: 2, luckRate: 0.3 } },
  { id: 'T077', name: '贵人相助', rarity: 2, tag: '幸运', desc: '关键时刻有人拉一把', eff: { luck: 2, eq: 1 } },
  { id: 'T078', name: '细节控', rarity: 2, tag: '智慧', desc: '一眼看出合同里的坑', eff: { iq: 2, luck: 1 } },
  { id: 'T079', name: '强记忆', rarity: 2, tag: '智慧', desc: '背书像复印', eff: { iq: 3, hp: -1 } },
  { id: 'T080', name: '睡眠质量好', rarity: 2, tag: '体质', desc: '沾枕头就睡，一觉天亮', eff: { hp: 3 } },
  { id: 'T081', name: '铁肺', rarity: 2, tag: '体质', desc: '长跑从不喘', eff: { hp: 2, luck: 1 } },
  { id: 'T082', name: '恢复力强', rarity: 2, tag: '体质', desc: '感冒睡一觉就好', eff: { hp: 3 } },
  { id: 'T083', name: '招财手', rarity: 2, tag: '幸运', desc: '摸过的生意都旺', eff: { luck: 2, luckRate: 0.2 } },
  { id: 'T084', name: '冷场终结者', rarity: 2, tag: '社交', desc: '多尴尬都能接住', eff: { eq: 2, iq: 1 } },
  { id: 'T085', name: '情绪稳定', rarity: 2, tag: '社交', desc: '天大的事也不慌', eff: { eq: 2, hp: 1 } },
  { id: 'T086', name: '耳聪目明', rarity: 2, tag: '智慧', desc: '隔着墙都能听清', eff: { iq: 2, luck: 1 } },
  { id: 'T087', name: '红颜薄命', rarity: 2, tag: '社交', desc: '好看是好看，就是命不长', eff: { eq: 3, luck: -1, lifespan: -50 } },
  { id: 'T088', name: '天生亲和', rarity: 2, tag: '社交', desc: '小孩和狗都喜欢你', eff: { eq: 3 } },
  { id: 'T089', name: '绝对音感', rarity: 2, tag: '智慧', desc: '走音半度都逃不过', eff: { iq: 3 } },
  { id: 'T090', name: '心魔缠身', rarity: 2, tag: '诡异', desc: '修炼越快，心魔越重', eff: { daoHeart: -3, progressRate: 0.3 } },
  { id: 'T091', name: '抗饿', rarity: 2, tag: '体质', desc: '饿一天也不带晕的', eff: { hp: 2, luck: 1 } },
  { id: 'T092', name: '会来事', rarity: 2, tag: '社交', desc: '领导一个眼神你就懂', eff: { eq: 2, iq: 1 } },
  { id: 'T093', name: '双灵根', rarity: 2, tag: '修仙', desc: '两条灵根，进境尚可', eff: { spiritRoot: 'dual', daoHeart: 1 } },
  { id: 'T094', name: '气感敏锐', rarity: 2, tag: '修仙', desc: '闭眼能感觉到灵气流动', eff: { progressRate: 0.4, daoHeart: 1 } },
  { id: 'T095', name: '经脉通畅', rarity: 2, tag: '修仙', desc: '灵气走得很顺', eff: { progressRate: 0.35, breakthrough: 0.03 } },
  { id: 'T096', name: '道心稳固', rarity: 2, tag: '修仙', desc: '心不慌，路不偏', eff: { daoHeart: 4, breakthrough: 0.03 } },
  { id: 'T097', name: '顿悟体质', rarity: 2, tag: '修仙', desc: '常常灵光一闪就懂了', eff: { progressRate: 0.45, iq: 1 } },
  { id: 'T098', name: '丹药亲和', rarity: 2, tag: '修仙', desc: '吃丹吸收比别人多', eff: { progressRate: 0.3, daoHeart: 2 } },
  { id: 'T099', name: '剑骨', rarity: 2, tag: '修仙', desc: '天生适合握剑', eff: { breakthrough: 0.05, hp: 1 } },
  { id: 'T100', name: '五行亲和', rarity: 2, tag: '修仙', desc: '五行都沾一点', eff: { spiritRoot: 'triple', progressRate: 0.4 } },

  // ---------------- 仙品（3） 25 条 ----------------
  { id: 'T101', name: '神童', rarity: 3, tag: '智慧', desc: '三岁背诗，五岁跳级', eff: { iq: 3, lifespan: 20 } },
  { id: 'T102', name: '百病不侵', rarity: 3, tag: '体质', desc: '一辈子没进过医院', eff: { hp: 3, lifespan: 50 } },
  { id: 'T103', name: '长袖善舞', rarity: 3, tag: '社交', desc: '到哪都吃得开', eff: { eq: 3, luck: 1 } },
  { id: 'T104', name: '天赐良机', rarity: 3, tag: '幸运', desc: '好事总赶巧砸到你头上', eff: { luck: 3, luckRate: 0.4 } },
  { id: 'T105', name: '铁壁', rarity: 3, tag: '体质', desc: '撞不坏也摔不烂', eff: { hp: 3, lifespan: 30 } },
  { id: 'T106', name: '商业嗅觉', rarity: 3, tag: '智慧', desc: '风口还没起你就站好了', eff: { iq: 2, luck: 2, lifespan: 10 } },
  { id: 'T107', name: '舌灿莲花', rarity: 3, tag: '社交', desc: '死的都能说活', eff: { eq: 3, iq: 1 } },
  { id: 'T108', name: '命运宠儿', rarity: 3, tag: '幸运', desc: '老天爷的亲儿子', eff: { luck: 3, luckRate: 0.45 } },
  { id: 'T109', name: '过目成诵', rarity: 3, tag: '智慧', desc: '看一遍就能背下来', eff: { iq: 3, lifespan: 20 } },
  { id: 'T110', name: '铁胃铜肠', rarity: 3, tag: '体质', desc: '生冷不忌，百毒不侵', eff: { hp: 3, lifespan: 20 } },
  { id: 'T111', name: '众星捧月', rarity: 3, tag: '社交', desc: '走到哪都是焦点', eff: { eq: 3, luck: 1 } },
  { id: 'T112', name: '时来运转', rarity: 3, tag: '幸运', desc: '低谷之后必有转机', eff: { luck: 2, luckRate: 0.4 } },
  { id: 'T113', name: '心如止水', rarity: 3, tag: '智慧', desc: '泰山崩于前面不改色', eff: { iq: 2, eq: 2, lifespan: 30 } },
  { id: 'T114', name: '铜墙铁壁', rarity: 3, tag: '体质', desc: '打不死的小强', eff: { hp: 3, lifespan: 20 } },
  { id: 'T115', name: '点石成金', rarity: 3, tag: '幸运', desc: '随便一做就赚钱', eff: { iq: 2, luck: 2, lifespan: 20 } },
  { id: 'T116', name: '天灵根', rarity: 3, tag: '修仙', desc: '万中无一的修炼奇才', eff: { spiritRoot: 'heaven', progressRate: 0.6, daoHeart: 2 } },
  { id: 'T117', name: '单灵根', rarity: 3, tag: '修仙', desc: '纯粹到极致的灵根', eff: { spiritRoot: 'single', progressRate: 0.5, breakthrough: 0.05 } },
  { id: 'T118', name: '宿慧', rarity: 3, tag: '修仙', desc: '前世似乎修行过', eff: { iq: 3, progressRate: 0.5, daoHeart: 3 } },
  { id: 'T119', name: '玲珑道心', rarity: 3, tag: '修仙', desc: '心魔难侵，道途坦荡', eff: { daoHeart: 6, breakthrough: 0.08 } },
  { id: 'T120', name: '破窍天赋', rarity: 3, tag: '修仙', desc: '卡关时总能一冲而过', eff: { breakthrough: 0.1, progressRate: 0.4 } },
  { id: 'T121', name: '灵气漩涡', rarity: 3, tag: '修仙', desc: '灵气自动往你身上钻', eff: { progressRate: 0.7, hp: 1 } },
  { id: 'T122', name: '剑心通明', rarity: 3, tag: '修仙', desc: '手中无剑，心中有剑', eff: { breakthrough: 0.08, daoHeart: 4 } },
  { id: 'T123', name: '夺天造化', rarity: 3, tag: '修仙', desc: '老天追着喂饭', eff: { progressRate: 0.6, breakthrough: 0.06, lifespan: 60 } },
  { id: 'T124', name: '冰魄灵体', rarity: 3, tag: '修仙', desc: '寒气入体，修炼极快', eff: { spiritRoot: 'single', progressRate: 0.55, breakthrough: 0.06, hp: 1 } },
  { id: 'T125', name: '丹道天赋', rarity: 3, tag: '修仙', desc: '闻一闻就知道药性', eff: { progressRate: 0.5, daoHeart: 3, iq: 1 } },

  // ---------------- 神品（4） 6 条 ----------------
  { id: 'T126', name: '天命之子', rarity: 4, tag: '幸运', desc: '世界围着你转', eff: { luck: 4, luckRate: 0.5, lifespan: 100 } },
  { id: 'T127', name: '万古无一', rarity: 4, tag: '智慧', desc: '生而知之，无所不通', eff: { iq: 4, eq: 4, lifespan: 150 } },
  { id: 'T128', name: '仙骨天成', rarity: 4, tag: '修仙', desc: '生来就是修仙的料', eff: { spiritRoot: 'heaven', progressRate: 0.9, breakthrough: 0.12, daoHeart: 5, lifespan: 100 } },
  { id: 'T129', name: '混沌灵根', rarity: 4, tag: '修仙', desc: '传说中的最强灵根', eff: { spiritRoot: 'heaven', progressRate: 1.0, breakthrough: 0.15, daoHeart: 6 } },
  { id: 'T130', name: '上古道体', rarity: 4, tag: '修仙', desc: '上古大能转世之躯', eff: { spiritRoot: 'single', progressRate: 0.8, breakthrough: 0.12, daoHeart: 5, hp: 2 } },
  { id: 'T131', name: '天命所归', rarity: 4, tag: '修仙', desc: '天道都给你让路', eff: { progressRate: 0.7, breakthrough: 0.15, luckRate: 0.4, lifespan: 120 } }
,
  { id: 'T132', name: '双修之资', rarity: 4, tag: '修仙', desc: '可以同时走在两条路上', eff: { dualPath: true, iq: 1, daoHeart: 2 } },
  { id: 'T133', name: '杂学旁收', rarity: 3, tag: '智慧', desc: '什么都学一点，条条路都走得通', eff: { dualPath: true, iq: 2, eq: -1 } }
]
