/**
 * 诡异 / 神品 / 双修专属 / 梗 彩蛋词条
 * 见 docs/内容规范.md 第 1 节 + 第 3.5 节
 *
 * 只导出 TALENTS 数组；id 段 T481 ~ T620
 * 分块：
 *   A 诡异命运（tag 诡异）
 *   B 神品强力（rarity 4）
 *   C 双修专属（tag 双修，eff.dualPath = true）
 *   D 梗/生活彩蛋（tag 梗）
 *
 * eff 支持：iq eq hp luck / lifespan / progressRate / breakthrough / luckRate /
 *   flag / spiritRoot / forbidCultivation / daoHeart / dieChance / enterPath / dualPath / sp
 */
export const TALENTS = [
  // ================= A. 诡异 / 命运（33 条） =================
  { id: 'T481', name: '先天道体', rarity: 3, tag: '诡异', desc: '修炼极快，寿元却受损', eff: { spiritRoot: 'single', progressRate: 0.5, breakthrough: 0.05, lifespan: -60, flag: 'innate_dao_body' } },
  { id: 'T482', name: '夺舍体质', rarity: 2, tag: '诡异', desc: '体内好像住着另一个人', eff: { forbidCultivation: true, iq: 2, eq: -2, lifespan: -30, flag: 'body_seized' } },
  { id: 'T483', name: '脑子有坑', rarity: 1, tag: '诡异', desc: '偶尔灵光，偶尔失智', eff: { iq: 2, eq: -3, luck: 1, flag: 'brain_hole' } },
  { id: 'T484', name: '命里带煞', rarity: 2, tag: '诡异', desc: '煞气随身，六亲缘薄', eff: { eq: -3, luck: 2, lifespan: -25, flag: 'ill_fated' } },
  { id: 'T485', name: '天机蒙蔽', rarity: 2, tag: '诡异', desc: '幸运忽好忽坏说不准', eff: { luck: 3, luckRate: -0.3, flag: 'veiled_fate' } },
  { id: 'T486', name: '前世记忆', rarity: 3, tag: '诡异', desc: '生来就记得另一世', eff: { spiritRoot: 'dual', daoHeart: 3, lifespan: -20, flag: 'past_life' } },
  { id: 'T487', name: '梦中授道', rarity: 2, tag: '诡异', desc: '梦里有人教我修行', eff: { progressRate: 0.5, eq: -2, flag: 'dream_teacher' } },
  { id: 'T488', name: '活不过三十', rarity: 3, tag: '诡异', desc: '命数只到而立之前', eff: { iq: 1, eq: 1, hp: 1, luck: 1, lifespan: -70, flag: 'short_life' } },
  { id: 'T489', name: '诡眼', rarity: 2, tag: '诡异', desc: '能看见不该看的东西', eff: { iq: 2, eq: -2, luck: 1, flag: 'ghost_eye' } },
  { id: 'T490', name: '阴年阴月生', rarity: 2, tag: '诡异', desc: '出生时辰阴气极重', eff: { spiritRoot: 'pseudo', luck: 2, lifespan: -20, flag: 'yin_birth' } },
  { id: 'T491', name: '阎王不收', rarity: 3, tag: '诡异', desc: '死过一回又活过来', eff: { dieChance: 0.03, hp: 3, lifespan: 30, flag: 'death_denied' } },
  { id: 'T492', name: '撞客', rarity: 2, tag: '诡异', desc: '身上跟着不干净的东西', eff: { dieChance: 0.04, luck: 3, eq: -3, flag: 'haunted' } },
  { id: 'T493', name: '借命', rarity: 3, tag: '诡异', desc: '借来的寿元终要还', eff: { spiritRoot: 'heaven', progressRate: 0.45, lifespan: -40, flag: 'borrow_life' } },
  { id: 'T494', name: '双瞳', rarity: 3, tag: '诡异', desc: '眼中还有一只眼睛', eff: { iq: 2, luck: 2, eq: -2, flag: 'double_pupil' } },
  { id: 'T495', name: '出生没哭', rarity: 2, tag: '诡异', desc: '生下来就没掉过泪', eff: { eq: -3, daoHeart: 4, breakthrough: 0.05, flag: 'no_cry' } },
  { id: 'T496', name: '梦里杀人', rarity: 2, tag: '诡异', desc: '梦里的债醒来还记得', eff: { hp: 2, eq: -2, progressRate: 0.35, flag: 'dream_kill' } },
  { id: 'T497', name: '命犯孤辰', rarity: 2, tag: '诡异', desc: '注定一个人走到底', eff: { eq: -3, luck: 3, lifespan: -20, flag: 'lonely_star' } },
  { id: 'T498', name: '有人喊名', rarity: 1, tag: '诡异', desc: '半夜总有人喊我名字', eff: { eq: -2, iq: 2, flag: 'called_name' } },
  { id: 'T499', name: '通阴', rarity: 2, tag: '诡异', desc: '能和另一个世界说话', eff: { iq: 2, eq: -2, flag: 'spirit_talk' } },
  { id: 'T500', name: '煞星', rarity: 1, tag: '诡异', desc: '走到哪都带点煞气', eff: { hp: 1, eq: -3, luck: 2, flag: 'sha_star' } },
  { id: 'T501', name: '死过一次', rarity: 3, tag: '诡异', desc: '从那以后什么都不怕', eff: { dieChance: 0.04, hp: 3, daoHeart: 3, flag: 'died_once' } },
  { id: 'T502', name: '阴德厚', rarity: 2, tag: '诡异', desc: '积了阴德，鬼都让路', eff: { luck: 2, lifespan: 40, progressRate: 0.2, flag: 'yin_deed' } },
  { id: 'T503', name: '早夭之相', rarity: 2, tag: '诡异', desc: '相士说活不过弱冠', eff: { lifespan: -50, luck: 3, flag: 'early_death' } },
  { id: 'T504', name: '游魂附体', rarity: 1, tag: '诡异', desc: '总觉得自己少了一魄', eff: { iq: -1, luck: 2, eq: -2, flag: 'wandering_soul' } },
  { id: 'T505', name: '命中有劫', rarity: 3, tag: '诡异', desc: '大劫在前，福祸难料', eff: { luck: 3, progressRate: 0.4, breakthrough: -0.05, flag: 'fate_trial' } },
  { id: 'T506', name: '天弃之子', rarity: 3, tag: '诡异', desc: '老天不要，我偏要修', eff: { luck: -3, progressRate: 0.6, breakthrough: 0.1, flag: 'abandoned' } },
  { id: 'T507', name: '见鬼体质', rarity: 2, tag: '诡异', desc: '一年到头都在撞邪', eff: { iq: 2, luck: 2, eq: -2, flag: 'see_ghost' } },
  { id: 'T508', name: '续命术', rarity: 3, tag: '诡异', desc: '用别人的命续自己的', eff: { lifespan: 60, hp: -2, eq: -2, flag: 'life_extension' } },
  { id: 'T509', name: '阴阳眼', rarity: 2, tag: '诡异', desc: '白天黑夜看的不一样', eff: { iq: 1, luck: 2, eq: -1, flag: 'yin_yang_eye' } },
  { id: 'T510', name: '命中缺金', rarity: 1, tag: '诡异', desc: '算命的说五行缺金', eff: { luck: -1, iq: 2, flag: 'lack_metal' } },
  { id: 'T511', name: '鬼打墙', rarity: 1, tag: '诡异', desc: '总在原地绕圈圈', eff: { luck: -2, hp: 2, iq: 1, flag: 'ghost_wall' } },
  { id: 'T512', name: '天生煞体', rarity: 3, tag: '诡异', desc: '煞气入体，修行极猛', eff: { hp: 2, eq: -2, progressRate: 0.45, breakthrough: 0.05, flag: 'sha_body' } },
  { id: 'T513', name: '诡异之种', rarity: 4, tag: '诡异', desc: '体内埋着一颗诡异种子', eff: { progressRate: 0.6, breakthrough: 0.1, daoHeart: -4, lifespan: -30, flag: 'weird_seed' } },

  // ================= B. 神品强力（21 条，均 rarity 4） =================
  { id: 'T514', name: '生而知之', rarity: 4, tag: '智慧', desc: '落地就懂天地至理', eff: { iq: 4, progressRate: 0.3, lifespan: 60, flag: 'born_knowing' } },
  { id: 'T515', name: '天生道种', rarity: 4, tag: '修仙', desc: '生来就是修道的料', eff: { spiritRoot: 'heaven', progressRate: 0.5, breakthrough: 0.08, daoHeart: 4, flag: 'dao_seed' } },
  { id: 'T516', name: '万法归一', rarity: 4, tag: '修仙', desc: '万般法门最后都通', eff: { iq: 2, progressRate: 0.6, breakthrough: 0.05, flag: 'all_laws_one' } },
  { id: 'T517', name: '气运加身', rarity: 4, tag: '幸运', desc: '气运缠身，逢凶化吉', eff: { luck: 4, luckRate: 0.5, lifespan: 80, flag: 'fortune_body' } },
  { id: 'T518', name: '晚成大器', rarity: 4, tag: '智慧', desc: '前半生平平，后半生爆', eff: { iq: 3, progressRate: 0.45, lifespan: 100, flag: 'late_bloom' } },
  { id: 'T519', name: '道心无瑕', rarity: 4, tag: '修仙', desc: '心如琉璃，不染尘埃', eff: { eq: 3, daoHeart: 8, breakthrough: 0.08, flag: 'pure_heart' } },
  { id: 'T520', name: '圣体天成', rarity: 4, tag: '体质', desc: '肉身已是半圣之姿', eff: { hp: 4, lifespan: 120, progressRate: 0.3, flag: 'holy_body' } },
  { id: 'T521', name: '法神传承', rarity: 4, tag: '智慧', desc: '识海里刻着上古法神', eff: { iq: 3, progressRate: 0.5, breakthrough: 0.1, flag: 'mage_legacy' } },
  { id: 'T522', name: '机械飞升图', rarity: 4, tag: '智慧', desc: '脑中有一张飞升蓝图', eff: { iq: 4, progressRate: 0.5, hp: -2, flag: 'mech_ascend' } },
  { id: 'T523', name: '双脉同修', rarity: 4, tag: '修仙', desc: '两条经脉同时运转', eff: { dualPath: true, iq: 2, progressRate: 0.5, breakthrough: 0.06, flag: 'twin_meridian' } },
  { id: 'T524', name: '通玄', rarity: 4, tag: '修仙', desc: '常于无声处听见天道', eff: { iq: 3, breakthrough: 0.12, progressRate: 0.4, flag: 'mystic' } },
  { id: 'T525', name: '天命神授', rarity: 4, tag: '幸运', desc: '天命直接灌进脑子里', eff: { luck: 4, luckRate: 0.6, lifespan: 100, flag: 'divine_grant' } },
  { id: 'T526', name: '造化之体', rarity: 4, tag: '体质', desc: '身负天地造化之力', eff: { hp: 2, progressRate: 0.6, breakthrough: 0.1, lifespan: 80, flag: 'creation_body' } },
  { id: 'T527', name: '道法自然', rarity: 4, tag: '修仙', desc: '一举一动皆合天道', eff: { progressRate: 0.55, breakthrough: 0.08, daoHeart: 6, flag: 'nature_dao' } },
  { id: 'T528', name: '无相灵根', rarity: 4, tag: '修仙', desc: '灵根无相，变化万千', eff: { spiritRoot: 'single', progressRate: 0.7, breakthrough: 0.12, flag: 'formless_root' } },
  { id: 'T529', name: '太初道体', rarity: 4, tag: '修仙', desc: '带着太初之气降生', eff: { spiritRoot: 'heaven', progressRate: 0.65, breakthrough: 0.1, daoHeart: 5, lifespan: 60, flag: 'primordial_body' } },
  { id: 'T530', name: '神机妙算', rarity: 4, tag: '幸运', desc: '掐指一算便知吉凶', eff: { iq: 4, luck: 3, luckRate: 0.3, flag: 'divine_calc' } },
  { id: 'T531', name: '龙象之力', rarity: 4, tag: '体质', desc: '一出生就有龙象之力', eff: { hp: 4, progressRate: 0.3, breakthrough: 0.06, flag: 'dragon_elephant' } },
  { id: 'T532', name: '涅槃之体', rarity: 4, tag: '体质', desc: '死了还能从火里重生', eff: { hp: 3, lifespan: 120, progressRate: 0.4, flag: 'nirvana_body' } },
  { id: 'T533', name: '千秋道骨', rarity: 4, tag: '修仙', desc: '道骨千秋，与天同寿', eff: { spiritRoot: 'heaven', daoHeart: 7, breakthrough: 0.1, lifespan: 150, flag: 'eternal_bone' } },
  { id: 'T534', name: '诸天垂青', rarity: 4, tag: '幸运', desc: '诸天都愿意帮你一把', eff: { luck: 4, luckRate: 0.5, progressRate: 0.3, lifespan: 90, flag: 'heaven_favor' } },

  // ================= C. 双修专属（24 条，均带 eff.dualPath） =================
  { id: 'T535', name: '阴阳相济', rarity: 3, tag: '双修', desc: '阴阳互济，两路同涨', eff: { dualPath: true, progressRate: 0.4, luck: 1, flag: 'yin_yang_harmony' } },
  { id: 'T536', name: '文武双全', rarity: 3, tag: '双修', desc: '文能提笔，武能上马', eff: { dualPath: true, iq: 2, eq: 2, flag: 'civil_martial' } },
  { id: 'T537', name: '一心二用', rarity: 2, tag: '双修', desc: '左手画方，右手画圆', eff: { dualPath: true, iq: 2, eq: -1, flag: 'dual_mind' } },
  { id: 'T538', name: '跨界天才', rarity: 4, tag: '双修', desc: '什么领域都学得飞快', eff: { dualPath: true, iq: 3, progressRate: 0.3, flag: 'cross_genius' } },
  { id: 'T539', name: '杂而不精', rarity: 2, tag: '双修', desc: '样样都通，样样稀松', eff: { dualPath: true, iq: 2, eq: -1, progressRate: -0.2, flag: 'jack_all' } },
  { id: 'T540', name: '双脉天生', rarity: 3, tag: '双修', desc: '天生两条修行脉络', eff: { dualPath: true, progressRate: 0.35, flag: 'dual_meridian' } },
  { id: 'T541', name: '佛道双修', rarity: 3, tag: '双修', desc: '一手念珠，一手符箓', eff: { dualPath: true, daoHeart: 4, progressRate: 0.3, flag: 'buddha_dao' } },
  { id: 'T542', name: '魔武双修', rarity: 3, tag: '双修', desc: '魔气与气血同流', eff: { dualPath: true, hp: 2, progressRate: 0.3, breakthrough: -0.03, flag: 'demon_martial' } },
  { id: 'T543', name: '剑心文胆', rarity: 3, tag: '双修', desc: '以文入剑，以剑证道', eff: { dualPath: true, iq: 2, breakthrough: 0.05, flag: 'sword_scholar' } },
  { id: 'T544', name: '左右开弓', rarity: 3, tag: '双修', desc: '两只手各练一门', eff: { dualPath: true, hp: 1, progressRate: 0.25, flag: 'both_hands' } },
  { id: 'T545', name: '双生灵根', rarity: 3, tag: '双修', desc: '一对灵根，两路并行', eff: { dualPath: true, spiritRoot: 'dual', progressRate: 0.3, flag: 'twin_root' } },
  { id: 'T546', name: '两路皆通', rarity: 2, tag: '双修', desc: '走哪条路都不算外行', eff: { dualPath: true, iq: 1, progressRate: 0.2, flag: 'both_paths' } },
  { id: 'T547', name: '兼修之才', rarity: 3, tag: '双修', desc: '同时修两门也不落下', eff: { dualPath: true, iq: 2, progressRate: 0.25, flag: 'poly_talent' } },
  { id: 'T548', name: '两不相误', rarity: 3, tag: '双修', desc: '两条路互不耽误', eff: { dualPath: true, luck: 2, progressRate: 0.2, flag: 'no_mutual_harm' } },
  { id: 'T549', name: '相生相克', rarity: 3, tag: '双修', desc: '两股力量相生相克', eff: { dualPath: true, hp: 2, progressRate: 0.45, breakthrough: -0.05, flag: 'mutual_restraint' } },
  { id: 'T550', name: '双核思维', rarity: 3, tag: '双修', desc: '脑子里像有两颗CPU', eff: { dualPath: true, iq: 3, progressRate: 0.2, flag: 'dual_core' } },
  { id: 'T551', name: '身心双修', rarity: 3, tag: '双修', desc: '炼体的同时也在炼心', eff: { dualPath: true, hp: 2, daoHeart: 3, progressRate: 0.25, flag: 'body_mind' } },
  { id: 'T552', name: '百艺通', rarity: 3, tag: '双修', desc: '什么都懂一点门道', eff: { dualPath: true, iq: 2, eq: 2, progressRate: 0.15, flag: 'hundred_arts' } },
  { id: 'T553', name: '两栖天才', rarity: 3, tag: '双修', desc: '在哪条路上都吃得开', eff: { dualPath: true, iq: 2, hp: 2, progressRate: 0.25, flag: 'amphibious' } },
  { id: 'T554', name: '通吃体质', rarity: 3, tag: '双修', desc: '什么体系都能吸收', eff: { dualPath: true, progressRate: 0.3, lifespan: -20, flag: 'all_eater' } },
  { id: 'T555', name: '二刀流', rarity: 3, tag: '双修', desc: '双手各持一把刀', eff: { dualPath: true, hp: 2, iq: 1, breakthrough: 0.03, flag: 'two_sword' } },
  { id: 'T556', name: '阴阳同体', rarity: 3, tag: '双修', desc: '一身兼具阴阳两气', eff: { dualPath: true, progressRate: 0.4, luck: 2, lifespan: -30, flag: 'yin_yang_body' } },
  { id: 'T557', name: '跨界宗匠', rarity: 4, tag: '双修', desc: '两条路都修到宗师', eff: { dualPath: true, progressRate: 0.5, breakthrough: 0.06, flag: 'cross_master' } },
  { id: 'T558', name: '双道奇才', rarity: 3, tag: '双修', desc: '两道同修，天资卓绝', eff: { dualPath: true, iq: 2, progressRate: 0.45, flag: 'dual_dao_genius' } },

  // ================= D. 梗 / 生活彩蛋（40 条） =================
  { id: 'T559', name: '键盘侠', rarity: 1, tag: '梗', desc: '网上重拳出击', eff: { eq: 1, hp: -1, flag: 'keyboard_warrior' } },
  { id: 'T560', name: '网络判官', rarity: 1, tag: '梗', desc: '见谁都想判个对错', eff: { iq: 1, eq: -1, flag: 'net_judge' } },
  { id: 'T561', name: '干饭人', rarity: 1, tag: '梗', desc: '干饭不积极，思想有问题', eff: { hp: 2, iq: -1, flag: 'rice_man' } },
  { id: 'T562', name: '永远在减肥', rarity: 1, tag: '梗', desc: '明天开始，真的', eff: { hp: 1, eq: 1, luck: -1, flag: 'always_diet' } },
  { id: 'T563', name: '假装很忙', rarity: 1, tag: '梗', desc: '键盘敲得比谁都响', eff: { eq: 1, iq: -1, flag: 'fake_busy' } },
  { id: 'T564', name: '摸鱼大师', rarity: 2, tag: '梗', desc: '上班八小时摸鱼七小时', eff: { iq: 1, hp: 1, flag: 'slack_master' } },
  { id: 'T565', name: '小时候的梦想', rarity: 2, tag: '梗', desc: '想当宇航员来着', eff: { iq: 1, luck: 1, flag: 'child_dream' } },
  { id: 'T566', name: '给自己写信', rarity: 2, tag: '梗', desc: '写给十年后的自己', eff: { eq: 1, daoHeart: 2, flag: 'self_letter' } },
  { id: 'T567', name: '爱好成职业', rarity: 2, tag: '梗', desc: '把喜欢的事做成了工作', eff: { iq: 2, eq: 1, flag: 'hobby_job' } },
  { id: 'T568', name: '表情包大师', rarity: 1, tag: '梗', desc: '斗图从没输过', eff: { eq: 2, iq: -1, flag: 'meme_master' } },
  { id: 'T569', name: '熬夜修仙', rarity: 2, tag: '梗', desc: '白天上班，夜里修仙', eff: { hp: -1, progressRate: 0.3, flag: 'stay_up_cultivate' } },
  { id: 'T570', name: '奶茶续命', rarity: 1, tag: '梗', desc: '一天不喝就浑身难受', eff: { hp: 1, luck: 1, lifespan: -5, flag: 'milk_tea' } },
  { id: 'T571', name: '快递拆箱', rarity: 1, tag: '梗', desc: '拆快递比过年还开心', eff: { luck: 1, eq: 1, flag: 'unbox' } },
  { id: 'T572', name: '追剧狂魔', rarity: 1, tag: '梗', desc: '一集接一集停不下来', eff: { iq: -1, eq: 2, flag: 'drama_addict' } },
  { id: 'T573', name: '手游肝帝', rarity: 1, tag: '梗', desc: '凌晨四点还在打副本', eff: { hp: -1, iq: 1, flag: 'mobile_game' } },
  { id: 'T574', name: '早八人', rarity: 1, tag: '梗', desc: '每周五天灵魂出窍', eff: { hp: -1, eq: 1, flag: 'morning_person' } },
  { id: 'T575', name: '打工人魂', rarity: 1, tag: '梗', desc: '打工才是正经事', eff: { hp: 1, luck: -1, flag: 'worker_soul' } },
  { id: 'T576', name: '省钱达人', rarity: 2, tag: '梗', desc: '羊毛薅得明明白白', eff: { luck: 1, iq: 1, flag: 'save_money' } },
  { id: 'T577', name: '点单纠结', rarity: 1, tag: '梗', desc: '菜单看十分钟没点', eff: { iq: -1, eq: 1, flag: 'order_hesitate' } },
  { id: 'T578', name: '社牛', rarity: 2, tag: '梗', desc: '和谁都能聊三小时', eff: { eq: 3, iq: -1, flag: 'social_cow' } },
  { id: 'T579', name: '颜值担当', rarity: 1, tag: '梗', desc: '合影永远站C位', eff: { eq: 2, iq: -1, flag: 'beauty' } },
  { id: 'T580', name: '反内卷', rarity: 2, tag: '梗', desc: '到点下班，绝不加班', eff: { hp: 1, iq: 1, eq: -1, flag: 'anti_involution' } },
  { id: 'T581', name: '电子木鱼', rarity: 2, tag: '梗', desc: '敲一敲，功德加一', eff: { daoHeart: 2, luck: 1, flag: 'e_woodfish' } },
  { id: 'T582', name: '云养猫', rarity: 1, tag: '梗', desc: '云吸猫，云铲屎', eff: { luck: 1, eq: 1, flag: 'cloud_cat' } },
  { id: 'T583', name: '健身卡吃灰', rarity: 1, tag: '梗', desc: '办卡那天就是巅峰', eff: { hp: -1, eq: 1, flag: 'gym_card' } },
  { id: 'T584', name: '深夜emo', rarity: 1, tag: '梗', desc: '一到半夜就多愁善感', eff: { iq: 1, eq: -1, hp: -1, flag: 'midnight_emo' } },
  { id: 'T585', name: '自拍狂', rarity: 1, tag: '梗', desc: '一天不发就浑身难受', eff: { eq: 2, luck: -1, flag: 'selfie' } },
  { id: 'T586', name: '转发锦鲤', rarity: 2, tag: '梗', desc: '抽奖前先转三条锦鲤', eff: { luck: 2, flag: 'koi_repost' } },
  { id: 'T587', name: '许愿池常客', rarity: 2, tag: '梗', desc: '路过就想投个硬币', eff: { luck: 2, eq: 1, flag: 'wish_pool' } },
  { id: 'T588', name: '捡漏王', rarity: 2, tag: '梗', desc: '二手市场淘到宝', eff: { luck: 1, iq: 1, flag: 'bargain_king' } },
  { id: 'T589', name: '明日复明日', rarity: 1, tag: '梗', desc: '今天的事明天再说', eff: { iq: -1, hp: 1, flag: 'later_later' } },
  { id: 'T590', name: '囤积癖', rarity: 1, tag: '梗', desc: '什么都不舍得扔', eff: { hp: 1, eq: -1, luck: 1, flag: 'hoarder' } },
  { id: 'T591', name: '断舍离', rarity: 2, tag: '梗', desc: '扔掉一半，神清气爽', eff: { iq: 1, eq: 1, flag: 'declutter' } },
  { id: 'T592', name: '科技绝缘', rarity: 1, tag: '梗', desc: '新软件永远学不会', eff: { iq: -1, progressRate: -0.1, flag: 'tech_insulated' } },
  { id: 'T593', name: '终身学习', rarity: 3, tag: '梗', desc: '活到老，学到老', eff: { iq: 2, lifespan: 20, flag: 'lifelong_learn' } },
  { id: 'T594', name: '佛系玩家', rarity: 1, tag: '梗', desc: '输赢随缘，开心就好', eff: { luck: 1, eq: 1, flag: 'buddhist_player' } },
  { id: 'T595', name: '考古爱好者', rarity: 2, tag: '梗', desc: '就爱研究老物件', eff: { iq: 1, lifespan: 10, flag: 'archaeology' } },
  { id: 'T596', name: '周末旅行家', rarity: 1, tag: '梗', desc: '一到周末就往外跑', eff: { eq: 1, hp: 1, flag: 'weekend_travel' } },
  { id: 'T597', name: '厨房杀手', rarity: 1, tag: '梗', desc: '做饭能把锅烧穿', eff: { hp: -1, eq: 1, flag: 'kitchen_killer' } },
  { id: 'T598', name: '外卖VIP', rarity: 1, tag: '梗', desc: '一天三顿全靠外卖', eff: { hp: -1, luck: 1, flag: 'takeout_vip' } }
]
