/**
 * 生活性格类天赋词条
 * 见 docs/内容规范.md 第 1 节
 *
 * 稀有度：1 凡品 / 2 灵品 / 3 仙品 / 4 神品
 * tag：性格 / 体质 / 社交 / 幸运 / 智慧 / 家庭 / 时代
 * id 范围：T201 ~ T340（共 140 条）
 *
 * 其中若干词条带 eff.flag，供人生事件 req.flags 联动：
 *   only_child / exam_master / landlord / star_chaser / cat_owner
 *   foodie / athlete / angler / collector / camper / musician
 */
export const TALENTS = [
  // ---------------- 凡品（1） 63 条 ----------------
  { id: 'T201', name: '讨好型', rarity: 1, tag: '性格', desc: '别人一皱眉你就道歉', eff: { eq: 1, iq: -1 } },
  { id: 'T202', name: '杠精', rarity: 1, tag: '性格', desc: '什么都要杠一句', eff: { eq: -2, iq: 1 } },
  { id: 'T203', name: '钝感', rarity: 1, tag: '性格', desc: '被骂三天才反应过来', eff: { hp: 1, iq: -1 } },
  { id: 'T204', name: '玻璃心', rarity: 1, tag: '性格', desc: '一句差评难受一周', eff: { eq: -1, hp: -1 } },
  { id: 'T205', name: '大心脏', rarity: 1, tag: '性格', desc: '上台紧张不到三秒', eff: { eq: 1, hp: 1 } },
  { id: 'T206', name: '极简主义', rarity: 1, tag: '性格', desc: '多一件东西都嫌乱', eff: { iq: 1, eq: -1 } },
  { id: 'T207', name: '完美主义', rarity: 1, tag: '性格', desc: '改到最后一秒还嫌差', eff: { iq: 1, hp: -1 } },
  { id: 'T208', name: '拖延晚期', rarity: 1, tag: '性格', desc: '能拖到明天绝不今天', eff: { iq: 1, hp: -1 } },
  { id: 'T209', name: '纠结体质', rarity: 1, tag: '性格', desc: '午饭能纠结到晚饭', eff: { iq: -1, luck: 1 } },
  { id: 'T210', name: '记仇', rarity: 1, tag: '性格', desc: '小本本记着每笔账', eff: { iq: 1, eq: -1 } },
  { id: 'T211', name: '嘴硬', rarity: 1, tag: '性格', desc: '错了也绝不认输', eff: { eq: -1, hp: 1 } },
  { id: 'T212', name: '爱哭包', rarity: 1, tag: '性格', desc: '看啥都能哭一场', eff: { eq: 1, hp: -1 } },
  { id: 'T213', name: '行动派', rarity: 1, tag: '性格', desc: '想到就去做', eff: { hp: 1, iq: -1 } },
  { id: 'T214', name: '空想家', rarity: 1, tag: '性格', desc: '计划做得比谁都漂亮', eff: { iq: 1, hp: -1 } },
  { id: 'T215', name: '洁癖', rarity: 1, tag: '性格', desc: '一天洗手二十遍', eff: { hp: -1, eq: -1 } },
  { id: 'T216', name: '暴脾气', rarity: 1, tag: '性格', desc: '一点就着', eff: { eq: -2, hp: -1 } },
  { id: 'T217', name: '内耗型', rarity: 1, tag: '性格', desc: '想太多睡不好', eff: { hp: -2, iq: -1 } },
  { id: 'T218', name: '社恐晚期', rarity: 1, tag: '性格', desc: '人多就喘不上气', eff: { eq: -2, hp: -1 } },
  { id: 'T219', name: '易胖体质', rarity: 1, tag: '体质', desc: '喝水都长肉', eff: { hp: -1, eq: -1 } },
  { id: 'T220', name: '过敏体质', rarity: 1, tag: '体质', desc: '花粉灰尘都惹不起', eff: { hp: -2 } },
  { id: 'T221', name: '平衡感差', rarity: 1, tag: '体质', desc: '平地也能摔一跤', eff: { hp: -1, luck: 1 } },
  { id: 'T222', name: '左右不分', rarity: 1, tag: '体质', desc: '导航让左转你偏右', eff: { iq: -1, luck: 1 } },
  { id: 'T223', name: '耐痛', rarity: 1, tag: '体质', desc: '打针从不眨眼', eff: { hp: 2 } },
  { id: 'T224', name: '怕冷', rarity: 1, tag: '体质', desc: '空调房里穿外套', eff: { hp: -1, iq: 1 } },
  { id: 'T225', name: '招蚊体质', rarity: 1, tag: '体质', desc: '蚊子只咬你一个', eff: { hp: -1, luck: 1 } },
  { id: 'T226', name: '晕车', rarity: 1, tag: '体质', desc: '坐半小时就翻江倒海', eff: { hp: -1, eq: -1 } },
  { id: 'T227', name: '中气足', rarity: 1, tag: '体质', desc: '喊一嗓子全场安静', eff: { hp: 1, eq: 1 } },
  { id: 'T228', name: '手脚冰凉', rarity: 1, tag: '体质', desc: '一年四季像块冰', eff: { hp: -1, eq: 1 } },
  { id: 'T229', name: '睡眠浅', rarity: 1, tag: '体质', desc: '一点动静就醒', eff: { hp: -1, iq: 1 } },
  { id: 'T230', name: '干饭快', rarity: 1, tag: '体质', desc: '三分钟解决一顿饭', eff: { hp: 1, eq: -1 } },
  { id: 'T231', name: '咖啡续命', rarity: 1, tag: '体质', desc: '一天三杯才开机', eff: { hp: -2, iq: 1 } },
  { id: 'T232', name: '血条厚', rarity: 1, tag: '体质', desc: '感冒从不吃药', eff: { hp: 2 } },
  { id: 'T233', name: '骨头软', rarity: 1, tag: '体质', desc: '下腰劈叉毫不费力', eff: { hp: 1, luck: 1 } },
  { id: 'T234', name: '嗜甜如命', rarity: 1, tag: '体质', desc: '牙医见了直摇头', eff: { hp: -2, eq: -1 } },
  { id: 'T235', name: '挑食', rarity: 1, tag: '体质', desc: '一桌菜没几样能吃', eff: { hp: -1, eq: -1 } },
  { id: 'T236', name: '冷场王', rarity: 1, tag: '社交', desc: '一开口全场安静', eff: { eq: -2 } },
  { id: 'T237', name: '敬语狂', rarity: 1, tag: '社交', desc: '您字从早挂到晚', eff: { eq: 1, iq: -1 } },
  { id: 'T238', name: '社交电量低', rarity: 1, tag: '社交', desc: '聚两小时充电三天', eff: { eq: -1, iq: 1 } },
  { id: 'T239', name: '捧场王', rarity: 1, tag: '社交', desc: '再冷的梗都接', eff: { eq: 2, iq: -1 } },
  { id: 'T240', name: '已读乱回', rarity: 1, tag: '社交', desc: '回消息全靠意念', eff: { eq: -2, hp: 1 } },
  { id: 'T241', name: '表情包富翁', rarity: 1, tag: '社交', desc: '斗图从没输过', eff: { eq: 2 } },
  { id: 'T242', name: '社牛', rarity: 1, tag: '社交', desc: '和陌生人聊成亲戚', eff: { eq: 2, iq: -1 } },
  { id: 'T243', name: '脸皮薄', rarity: 1, tag: '社交', desc: '被夸一句脸就红', eff: { eq: -1, iq: 1 } },
  { id: 'T244', name: '嘴笨', rarity: 1, tag: '社交', desc: '心里一堆话说不出', eff: { eq: -2, iq: -1 } },
  { id: 'T245', name: '非酋', rarity: 1, tag: '幸运', desc: '抽卡永远保底', eff: { luck: -2 } },
  { id: 'T246', name: '小确幸', rarity: 1, tag: '幸运', desc: '总能捡到一块钱', eff: { luck: 1, hp: 1 } },
  { id: 'T247', name: '红灯玄学', rarity: 1, tag: '幸运', desc: '一路红灯是常态', eff: { luck: -1, hp: 1 } },
  { id: 'T248', name: '雨神', rarity: 1, tag: '幸运', desc: '忘带伞必下雨', eff: { luck: -1, iq: 1 } },
  { id: 'T249', name: '排队玄学', rarity: 1, tag: '幸运', desc: '选的队一定最慢', eff: { luck: -2, iq: 1 } },
  { id: 'T250', name: '三分钟热度', rarity: 1, tag: '智慧', desc: '买书如山倒看书如抽丝', eff: { iq: 1, hp: -1 } },
  { id: 'T251', name: '考试型选手', rarity: 1, tag: '智慧', desc: '平时挂科大考超常', eff: { iq: 2, hp: -1 } },
  { id: 'T252', name: '笔迹工整', rarity: 1, tag: '智慧', desc: '字写得像印刷体', eff: { iq: 1, eq: -1 } },
  { id: 'T253', name: '网课钉子户', rarity: 1, tag: '智慧', desc: '买了课就没打开过', eff: { iq: -1, luck: 1 } },
  { id: 'T254', name: '词汇量低', rarity: 1, tag: '智慧', desc: '夸人永远只有两个字', eff: { iq: -1, eq: -1 } },
  { id: 'T255', name: '动手废', rarity: 1, tag: '智慧', desc: '装个书架能装反', eff: { iq: -1, hp: 1 } },
  { id: 'T256', name: '数码达人', rarity: 1, tag: '智慧', desc: '新玩意上手就会', eff: { iq: 1, eq: 1 } },
  { id: 'T257', name: '健忘', rarity: 1, tag: '智慧', desc: '刚说的话转头就忘', eff: { iq: -2, luck: -1 } },
  { id: 'T258', name: '家里开小卖部', rarity: 1, tag: '家庭', desc: '零食自由零花钱免谈', eff: { hp: 1, luck: 1 } },
  { id: 'T259', name: '独生子女', rarity: 1, tag: '家庭', desc: '全家资源都是你的', eff: { eq: 1, hp: -1, flag: 'only_child' } },
  { id: 'T260', name: '留守儿童', rarity: 1, tag: '家庭', desc: '一年见爸妈一次', eff: { eq: -1, hp: -1 } },
  { id: 'T261', name: '重组家庭', rarity: 1, tag: '家庭', desc: '多了两个不熟的亲戚', eff: { eq: -1, iq: 1 } },
  { id: 'T262', name: '外卖人生', rarity: 1, tag: '时代', desc: '厨房只是个摆设', eff: { hp: -1, iq: 1 } },
  { id: 'T263', name: '手机依赖', rarity: 1, tag: '时代', desc: '离开手机就心慌', eff: { iq: -1, luck: 1 } },

  // ---------------- 灵品（2） 45 条 ----------------
  { id: 'T264', name: '强运', rarity: 2, tag: '幸运', desc: '关键时刻总能蒙对', eff: { luck: 2, luckRate: 0.2 } },
  { id: 'T265', name: '锦鲤体质', rarity: 2, tag: '幸运', desc: '转发什么中什么', eff: { luck: 3, luckRate: 0.25 } },
  { id: 'T266', name: '乌鸦嘴', rarity: 2, tag: '幸运', desc: '说谁倒霉谁倒霉', eff: { luck: -2, eq: 1 } },
  { id: 'T267', name: '逢考必过', rarity: 2, tag: '智慧', desc: '再难的卷子也能过', eff: { iq: 2, luck: 1, flag: 'exam_master' } },
  { id: 'T268', name: '反套路', rarity: 2, tag: '智慧', desc: '一眼看穿所有套路', eff: { iq: 3 } },
  { id: 'T269', name: '过目成图', rarity: 2, tag: '智慧', desc: '看一遍能默画结构', eff: { iq: 3, hp: -1 } },
  { id: 'T270', name: 'DDL战士', rarity: 2, tag: '性格', desc: '不到最后一天不动手', eff: { iq: 2, hp: -1 } },
  { id: 'T271', name: '强迫摆正', rarity: 2, tag: '性格', desc: '看见歪的就想扶正', eff: { iq: 2, eq: -1 } },
  { id: 'T272', name: '神经大条', rarity: 2, tag: '性格', desc: '丢三落四也不慌', eff: { hp: 2, iq: -1 } },
  { id: 'T273', name: '反内耗体质', rarity: 2, tag: '性格', desc: '关了手机就真放下', eff: { hp: 2, eq: 1 } },
  { id: 'T274', name: '毒舌', rarity: 2, tag: '性格', desc: '一句话把人说沉默', eff: { eq: 1, iq: 2, luck: -1 } },
  { id: 'T275', name: '冷幽默', rarity: 2, tag: '性格', desc: '笑点总慢半拍', eff: { eq: 2, iq: 1 } },
  { id: 'T276', name: '高敏感', rarity: 2, tag: '性格', desc: '能听出话里的情绪', eff: { iq: 2, hp: -1 } },
  { id: 'T277', name: '共情力强', rarity: 2, tag: '社交', desc: '别人难过你也难受', eff: { eq: 2, hp: -1 } },
  { id: 'T278', name: '记名达人', rarity: 2, tag: '社交', desc: '见一面就喊得出名字', eff: { eq: 2, iq: 1 } },
  { id: 'T279', name: '饭局救场', rarity: 2, tag: '社交', desc: '冷场时你总能接上', eff: { eq: 2, luck: 1 } },
  { id: 'T280', name: '话里有话', rarity: 2, tag: '社交', desc: '听得出弦外之音', eff: { iq: 2, eq: 1 } },
  { id: 'T281', name: '直男发言', rarity: 2, tag: '社交', desc: '一句话得罪一桌人', eff: { eq: -2, iq: 1 } },
  { id: 'T282', name: '酒量好', rarity: 2, tag: '体质', desc: '桌上从没输过', eff: { hp: 2, eq: 1 } },
  { id: 'T283', name: '铁头睡', rarity: 2, tag: '体质', desc: '在哪都能睡着', eff: { hp: 2, iq: -1 } },
  { id: 'T284', name: '一吃就胖', rarity: 2, tag: '体质', desc: '体重只增不减', eff: { hp: -1, eq: -2 } },
  { id: 'T285', name: '耐力王', rarity: 2, tag: '体质', desc: '跑十公里还有力气', eff: { hp: 3, eq: -1 } },
  { id: 'T286', name: '天生神力', rarity: 2, tag: '体质', desc: '搬家不用请人', eff: { hp: 3 } },
  { id: 'T287', name: '五音不全', rarity: 2, tag: '智慧', desc: '唱歌从没在调上', eff: { eq: -2, iq: -1 } },
  { id: 'T288', name: '拍照手稳', rarity: 2, tag: '智慧', desc: '随手一拍就是大片', eff: { iq: 2, luck: 1 } },
  { id: 'T289', name: '时间管理', rarity: 2, tag: '智慧', desc: '一天能干三天的活', eff: { iq: 2, hp: 1 } },
  { id: 'T290', name: '数字敏感', rarity: 2, tag: '智慧', desc: '账本扫一眼就记住', eff: { iq: 2, luck: 1 } },
  { id: 'T291', name: '语言天赋', rarity: 2, tag: '智慧', desc: '学外语跟玩似的', eff: { iq: 2, eq: 1 } },
  { id: 'T292', name: '装傻高手', rarity: 2, tag: '智慧', desc: '心里门儿清脸上懵', eff: { eq: 1, iq: 2 } },
  { id: 'T293', name: '学渣逆袭', rarity: 2, tag: '智慧', desc: '越到后面越开窍', eff: { iq: 2, luck: 1 } },
  { id: 'T294', name: '过目就忘', rarity: 2, tag: '智慧', desc: '书翻完等于没看', eff: { iq: -2, luck: -1 } },
  { id: 'T295', name: '记忆宫殿', rarity: 2, tag: '智慧', desc: '东西放哪都记得', eff: { iq: 2, luck: 1 } },
  { id: 'T296', name: '拆迁户', rarity: 2, tag: '家庭', desc: '一夜之间家里有钱了', eff: { luck: 2, eq: 1, flag: 'landlord' } },
  { id: 'T297', name: '富二代', rarity: 2, tag: '家庭', desc: '从小没缺过钱', eff: { eq: 2, luck: 2, iq: -1 } },
  { id: 'T298', name: '书香门第', rarity: 2, tag: '家庭', desc: '家里书比人多', eff: { iq: 2, eq: 1 } },
  { id: 'T299', name: '父母是老师', rarity: 2, tag: '家庭', desc: '回家还要上课', eff: { iq: 2, hp: -1 } },
  { id: 'T300', name: '家里有矿', rarity: 2, tag: '家庭', desc: '零花钱没有上限', eff: { luck: 2, hp: 1 } },
  { id: 'T301', name: '隔代亲', rarity: 2, tag: '家庭', desc: '爷爷奶奶护到没边', eff: { hp: 2, eq: 1 } },
  { id: 'T302', name: '早八免疫', rarity: 2, tag: '时代', desc: '早八也能精神抖擞', eff: { hp: 2, iq: 1 } },
  { id: 'T303', name: '熬夜回血快', rarity: 2, tag: '时代', desc: '睡四小时满血复活', eff: { hp: 2, iq: -1 } },
  { id: 'T304', name: '外卖美食家', rarity: 2, tag: '时代', desc: '一眼挑中最香的店', eff: { iq: 1, luck: 2 } },
  { id: 'T305', name: '断网焦虑', rarity: 2, tag: '时代', desc: '没信号就坐立不安', eff: { iq: -1, hp: -1, luck: -1 } },
  { id: 'T306', name: '办了卡不去', rarity: 2, tag: '时代', desc: '健身卡只去过一次', eff: { hp: -1, luck: -1 } },
  { id: 'T307', name: '追星族', rarity: 2, tag: '时代', desc: '偶像一句话顶十句', eff: { eq: 2, hp: 1, flag: 'star_chaser' } },
  { id: 'T308', name: '养猫人', rarity: 2, tag: '时代', desc: '猫一叫人就软', eff: { eq: 2, hp: 1, flag: 'cat_owner' } },

  // ---------------- 仙品（3） 25 条 ----------------
  { id: 'T309', name: '社恐之神', rarity: 3, tag: '性格', desc: '人一多就想消失', eff: { eq: -3, hp: -1, iq: 2 } },
  { id: 'T310', name: '钝感力', rarity: 3, tag: '性格', desc: '天塌了也影响不到你', eff: { hp: 3, eq: 2 } },
  { id: 'T311', name: '超大心脏', rarity: 3, tag: '性格', desc: '越大的场面越稳', eff: { eq: 3, hp: 2 } },
  { id: 'T312', name: '全能社牛', rarity: 3, tag: '社交', desc: '到哪都是人群中心', eff: { eq: 3, luck: 1 } },
  { id: 'T313', name: '天生段子手', rarity: 3, tag: '社交', desc: '随口一句就是金句', eff: { eq: 3, iq: 1 } },
  { id: 'T314', name: '吃嘛嘛香', rarity: 3, tag: '体质', desc: '生冷不忌百毒不侵', eff: { hp: 3, lifespan: 20 } },
  { id: 'T315', name: '夜猫神', rarity: 3, tag: '体质', desc: '夜里脑子转得最快', eff: { iq: 3, hp: -1, lifespan: -10 } },
  { id: 'T316', name: '运动怪物', rarity: 3, tag: '体质', desc: '天生运动员的料', eff: { hp: 3, eq: 1 } },
  { id: 'T317', name: '越压越强', rarity: 3, tag: '体质', desc: '压力越大状态越好', eff: { hp: 3, eq: 2 } },
  { id: 'T318', name: '听音辨曲', rarity: 3, tag: '智慧', desc: '听一遍就能弹出旋律', eff: { iq: 2, eq: 2, flag: 'musician' } },
  { id: 'T319', name: '商机雷达', rarity: 3, tag: '智慧', desc: '看什么都想得到商机', eff: { iq: 2, luck: 2, lifespan: 10 } },
  { id: 'T320', name: '考试之神', rarity: 3, tag: '智慧', desc: '没有你考不过的试', eff: { iq: 3, luck: 1 } },
  { id: 'T321', name: '学习机器', rarity: 3, tag: '智慧', desc: '看一遍就能举一反三', eff: { iq: 3, lifespan: 10 } },
  { id: 'T322', name: '天生好嗓', rarity: 3, tag: '智慧', desc: '开口就让人起疙瘩', eff: { iq: 2, eq: 2 } },
  { id: 'T323', name: '铁打身体', rarity: 3, tag: '体质', desc: '一辈子很少生病', eff: { hp: 3, lifespan: 30 } },
  { id: 'T324', name: '钞能力', rarity: 3, tag: '家庭', desc: '家里能解决大部分难题', eff: { luck: 3, eq: 1, lifespan: 10 } },
  { id: 'T325', name: '世家子弟', rarity: 3, tag: '家庭', desc: '人脉从出生就铺好', eff: { eq: 3, iq: 1 } },
  { id: 'T326', name: '长寿基因', rarity: 3, tag: '家庭', desc: '祖辈都活到九十多', eff: { lifespan: 30, hp: 2 } },
  { id: 'T327', name: '时代弄潮儿', rarity: 3, tag: '时代', desc: '总能踩中下一个风口', eff: { iq: 2, luck: 2, lifespan: 10 } },
  { id: 'T328', name: '网感天才', rarity: 3, tag: '时代', desc: '随手一发就是爆款', eff: { iq: 2, eq: 2, luck: 1 } },
  { id: 'T329', name: '美食家', rarity: 3, tag: '时代', desc: '舌头比仪器还准', eff: { iq: 2, hp: 1, flag: 'foodie' } },
  { id: 'T330', name: '健身狂魔', rarity: 3, tag: '时代', desc: '一天不练浑身难受', eff: { hp: 3, eq: 1, flag: 'athlete' } },
  { id: 'T331', name: '钓鱼佬', rarity: 3, tag: '时代', desc: '一坐一天心静如水', eff: { hp: 2, daoHeart: 3, flag: 'angler' } },
  { id: 'T332', name: '文玩收藏', rarity: 3, tag: '时代', desc: '一眼辨出真假', eff: { iq: 2, luck: 2, flag: 'collector' } },
  { id: 'T333', name: '露营达人', rarity: 3, tag: '时代', desc: '荒野里也能睡得香', eff: { hp: 3, luck: 1, flag: 'camper' } },

  // ---------------- 神品（4） 7 条 ----------------
  { id: 'T334', name: '世界主角', rarity: 4, tag: '幸运', desc: '好事总绕着你转', eff: { luck: 3, luckRate: 0.3, lifespan: 100 } },
  { id: 'T335', name: '天生圣体', rarity: 4, tag: '体质', desc: '百病不侵寿比松', eff: { hp: 3, lifespan: 80 } },
  { id: 'T336', name: '万中无一', rarity: 4, tag: '智慧', desc: '学什么都一点就通', eff: { iq: 3, luck: 2, lifespan: 60 } },
  { id: 'T337', name: '社交天花板', rarity: 4, tag: '社交', desc: '一句话让全场信服', eff: { eq: 3, luck: 2, lifespan: 50 } },
  { id: 'T338', name: '家财万贯', rarity: 4, tag: '家庭', desc: '几辈子都花不完', eff: { luck: 3, eq: 2, lifespan: 60 } },
  { id: 'T339', name: '时代之子', rarity: 4, tag: '时代', desc: '风口都追着你跑', eff: { iq: 3, luck: 3, lifespan: 60 } },
  { id: 'T340', name: '天选之人', rarity: 4, tag: '幸运', desc: '连老天都偏心你', eff: { luck: 3, luckRate: 0.3, lifespan: 80 } }
]
